runtime: python39  # Use Python 3.9
entrypoint: python app.py  # Entrypoint for your app

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65  # Target CPU utilization
  min_instances: 1  # Minimum number of instances
  max_instances: 2  # Maximum number of instances

# Environment variables (if needed)
env_variables:
  FLASK_ENV: production
  SECRET_KEY: 'your_secret_key'